### ISSUE TITLE
Use semantic versioning for future releases

### ISSUE THREAD

**Issue by johannesnicolaus** [pasmopy/pasmopy#72]
I was just browsing around and found that the releases do not seem to follow any versioning rules.
 
Maybe using semantic versioning https://semver.org/ for future releases will be easier for users?

Best,
Nico

**Comment by johannesnicolaus** [comment]
Cool, how about minor updates and patches?

**Comment by himoto** [comment]
Now I create versions as follows,
- MAJOR version -> kept 0
- MINOR version -> +1 when I add an important feature, but do not care whether it is backwards compatible or not
- PATCH version -> +1 with small fixes, updates, etc.

This versioning rule needs to be fixed but not sure how strictly I should follow semantic versioning.

**Comment by johannesnicolaus** [comment]
Important is subjective and I believe should not be a criteria for versioning, I would suggest the following for now:

MINOR -> +1 feature updates
PATCH -> +1 bug fixes

For example, I saw that v0.2.2 introduced new features compared to v0.2.1, and I think it should have been a bump to v0.3.0.
Just keep in mind that it should not matter how "important" changes are when versioning and that you shouldn't keep version numbers as small as possible.

**Comment by himoto** [comment]
OK, thanks!
